const fs=require('fs');
const rows=JSON.parse(fs.readFileSync('.work/flips2.json','utf8'));
const HO=require('./head_logic.js');
const obj=L=>n=>{const s=L.STATIONS.find(x=>x[0]===n)||L.STATIONS.find(x=>x[1]===n);return s?L.stToObj(s):null;};
const oh=obj(HO);
const dn=rows.filter(r=>r.old===2&&r.new===0);
const fastDn=dn.filter(r=>HO.beltV2(oh(r.S),oh(r.H),oh(r.P),true)===2);
const chain=['湛江','湛江西','海口','海口东','三亚','儋州','白马井','东方','文昌','琼海','万宁','徐闻'];
const inChain=fastDn.filter(r=>chain.indexOf(r.P)>=0).length;
console.log('fast 路径收紧共',fastDn.length,'条; 其中目的地属于雷州-海南链:',inChain);
console.log('不在链上的:', fastDn.filter(r=>chain.indexOf(r.P)<0).map(r=>r.S+'<->'+r.H+' 去'+r.P).join(' | ')||'(无)');
